version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"    
    depends_on:
      - sqlserver
    environment:
      # connection string
      ConnectionStrings__WebAPIConnectionString: "Server=sqlserver;Database=ZadanieLSI;User Id=sa;Password=MocneHaslo123;Encrypt=True;TrustServerCertificate=True;"
      ASPNETCORE_URLS: "http://0.0.0.0:80"
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "MocneHaslo123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"